CREATE TABLE Account (
	id SERIAL PRIMARY KEY,
	nick VARCHAR(64) UNIQUE NOT NULL,
	password VARCHAR(255),
	admin BOOLEAN
);

CREATE TABLE Priority (
	id SERIAL PRIMARY KEY,
	account_id INTEGER REFERENCES Account(id) ON DELETE CASCADE,
	priority INTEGER, -- isompi tärkeämpi, "baseline" 0
	name VARCHAR(64)
);

CREATE TABLE Task (
	id SERIAL PRIMARY KEY,
	account_id INTEGER REFERENCES Account(id) ON DELETE CASCADE,
	priority_id INTEGER REFERENCES Priority(id) ON DELETE SET NULL,
	task VARCHAR(255)
);

CREATE TABLE Category (
	id SERIAL PRIMARY KEY,
	account_id INTEGER REFERENCES Account(id) ON DELETE CASCADE,
	name VARCHAR(64)
);

CREATE TABLE TaskCategory (
	task_id INTEGER REFERENCES Task(id) ON DELETE CASCADE,
	category_id INTEGER REFERENCES Category(id) ON DELETE CASCADE
);
